### ISSUE TITLE
Next.js support as new `tech_stack`

### ISSUE THREAD

**Issue by simonaco** [github-starter-workflows/repo-analysis-partner#11]
**Name of the `tech_stack`**
Next

**Filenames to look for in the repository**
`package.json`
Optionally, it could also include `next.config.json`

**File extensions to look for in the repository**
`.js` 
`.ts` 

**Content/Regex to look for in the above-mentioned filename/extensions**
`package.json` file must include `next` in the dependencies list:
"dependencies": {
    "next": 

**Additional context**
[Example repo](https://github.com/vercel/nextjs-subscription-payments)

**Comment by tejasd1990** [comment]
hi @simonaco , is the optional file supposed to be `next.config.json`, or `next.config.js`? Can you confirm this?

**Comment by simonaco** [comment]
@tejasd1990 it should be `next.config.js` not `next.config.json`
