### ISSUE TITLE
Nuxt support as new `tech_stack`

### ISSUE THREAD

**Issue by simonaco** [github-starter-workflows/repo-analysis-partner#12]
**Name of the `tech_stack`**
Nuxt

**Filenames to look for in the repository**
`package.json`
Optionally, it could also include `nuxt.config.json`

**File extensions to look for in the repository**
`.js` 
`.ts` 
'.vue'

**Content/Regex to look for in the above-mentioned filename/extensions**
`package.json` file must include `nuxt` in the dependencies list:
"dependencies": {
    "nuxt": 

**Additional context**
[Example repo](https://github.com/wmui/essay)

**Comment by tejasd1990** [comment]
@simonaco , same as for `next`. Is the optional file `nuxt.config.js`? Also, is `.vue` a valid extension for nuxt?

**Comment by simonaco** [comment]
@tejasd1990 the optional file should be `nuxt.config.js`. Yes, `.vue` is a valid extension for files in a nuxt project, see an example here [nitro-demo](https://github.com/nuxt/nitro-demo)
