### ISSUE TITLE
Kustomize support new `tech_stack`

### ISSUE THREAD

**Issue by gambtho** [github-starter-workflows/repo-analysis-partner#19]
**Name of the `tech_stack`**
A distinct name for the `tech_stack`
Kustomize

**Filenames to look for in the repository**
This defines the name of the file used as the criteria of detection. For eg, the presence of `yarn.lock` is the detection criteria for `Yarn`.
kustomization.yaml

**File extensions to look for in the repository**
This defines the extensions of files used as the criteria of detection. For eg, the presence of `.csproj` extension is a detection criteria for `AspNetCore`.

.yaml

**Content/Regex to look for in the above-mentioned filename/extensions**
This defines the content to look for in the file with the name/extensions defined above. For eg, the presence of `<Project Sdk="Microsoft.NET.Sdk.Web">` in a file with extension `.csproj` is the detection criteria for `AspNetCore`

n/a

**Additional context**
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/README.md

**Comment by anuragc617** [comment]
@gambtho can you please provide the details on how to detect the Kustomize? Ex- look for Kustomize.yaml and service.yaml

**Comment by gambtho** [comment]
that information in in the description above...i'm not sure what you're asking beyond that

**Comment by gambtho** [comment]
specifically -- kutomization.yaml is the only file that would be unique -- everything else is just normal k8s yaml files
