### ISSUE TITLE
Symfony support as a new `tech_stack`

### ISSUE THREAD

**Issue by TheGarious** [github-starter-workflows/repo-analysis-partner#2]
**Name of the `tech_stack`**
The new tech_stack suggested is  `Symfony`.

**Filenames to look for in the repository**
The repository must have a composer.json file.

**Content/Regex to look for in the above-mentioned filename/extensions**

```json
{
    "require": {
        "symfony/framework-bundle": "4.4.*",
    }
}
```

**Comment by tejasd1990** [comment]
@TheGarious can you share a sample repo for `symfony`?

**Comment by TheGarious** [comment]
Hi @tejasd1990,

https://github.com/UnicornOfCodes/releasy-api

**Comment by tejasd1990** [comment]
we are working on adding this stack, will update once it is done
