### ISSUE TITLE
Improved support for `Kubernetes` tech stack

### ISSUE THREAD

**Issue by sabbour** [github-starter-workflows/repo-analysis-partner#21]
**Name of the `tech_stack`**
`Kubernetes`

**File extensions to look for in the repository**
*.yaml

**Content/Regex to look for in the above-mentioned filename/extensions**
Having *any* of the following in the YAML files
```
kind: Binding
kind: ComponentStatus
kind: ConfigMap
kind: Endpoints
kind: Event
kind: LimitRange
kind: Namespace
kind: Node
kind: NodeProxyOptions
kind: PersistentVolumeClaim
kind: PersistentVolume
kind: Pod
kind: PodAttachOptions
kind: Eviction
kind: PodExecOptions
kind: PodPortForwardOptions
kind: PodProxyOptions
kind: PodTemplate
kind: ReplicationController
kind: Scale
kind: ReplicationController
kind: ResourceQuota
kind: Secret
kind: ServiceAccount
kind: TokenRequest
kind: Service
kind: ServiceProxyOptions
```

List above is generated via this command:
```
for apipath in $(kubectl api-versions | sort | sed '/\//{H;1h;$!d;x}'); do
  version=${apipath#*/}
  api=${apipath%$version}
  api=${api%/}
  prefix="/api${api:+s}/"
  api=${api:-(core)}
  >&2 echo "${prefix}${apipath}: ${api}/${version}"
  kubectl get --raw "${prefix}${apipath}" | jq -r --arg api "${api}/${version}" '.resources | sort_by(.name) | .[]? | "kind: \(.kind)"'
done
```

**Additional context**
Right now, the **Get started with GitHub Actions** is not recommending Kubernetes actions for repositories that have Kubernetes manifests. This proposal is to improve the detection logic.

**Comment by Phantsure** [comment]
I am looking into this. Can you also provide a sample public repo to test the presence of tech_stack?

**Comment by sabbour** [comment]
@Phantsure here's one: https://github.com/Azure-Samples/azure-voting-app-redis

**Comment by Phantsure** [comment]
The above `Content/Regex` provided is exhaustive or just an example?

**Comment by sabbour** [comment]
@Phantsure that should cover most of it now

**Comment by bishal-pdMSFT** [comment]
@sabbour is there a sample repo which you want us to add to our test suite. the tests will run Scout on the repo and ensure that detected tech stacks are as expected.
The repo should be public and long lived for testing purpose.

**Comment by sabbour** [comment]
Let's use the same Azure samples repo above.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Phantsure** [comment]
We have added these changes. Now it can detect and show relevant deployment templates like below. This screenshot is from a fork of the sample repo you provided
<img width="1204" alt="Screenshot 2022-10-19 at 4 36 01 PM" src="https://user-images.githubusercontent.com/25999504/196674503-13ccd39e-3d21-4860-bee6-b57ce776a182.png">

**Comment by sabbour** [comment]
Have these been rolled out already? I just tried it on a fork and I don't see the same view:
![image](https://user-images.githubusercontent.com/103856/196758819-8b972264-ff86-43fb-a7cc-819ad5120e53.png)

**Comment by Phantsure** [comment]
You would need to update the repo in some way. It must be fetching from cache for you. 
Changes have already rolled out

**Comment by Phantsure** [comment]
@sabbour Hope the changes seem visible to you. Can we close this issue in that case?

**Comment by sabbour** [comment]
Please go ahead.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sabbour** [comment]
I just noticed the above list is missing
```
kind: Deployment
kind: StatefulSet
kind: ReplicaSet
kind: DaemonSet
kind: Ingress
```
@Phantsure  @bishal-pdMSFT  I must have missed pasting them in here.

**Comment by Phantsure** [comment]
@sabbour Have added these as well
