### ISSUE TITLE
Laravel support as a new `tech_stack`

### ISSUE THREAD

**Issue by TheGarious** [github-starter-workflows/repo-analysis-partner#3]
**Name of the `tech_stack`**
The new tech_stack suggested is  `Laravel`.

**Filenames to look for in the repository**
The repository must have a composer.json file.

**Content/Regex to look for in the above-mentioned filename/extensions**

```json
{
    "require": {
        "laravel/framework": "5.5.*",
    }
}
```

**Comment by tejasd1990** [comment]
@TheGarious can you share a sample repo for `laravel`?

**Comment by TheGarious** [comment]
Hi @tejasd1990,

https://github.com/octobercms/october

**Comment by anuragc617** [comment]
Added laravel.
